### ISSUE TITLE
How to use cog-tile-server

### ISSUE THREAD

**Issue by wenjunzhangp** [atararaksin/cog-tile-server#1]
I successfully ran this project, but I don’t know how to use it.
Question one：What is the parameter `uri` value assigned to, httpurl or disk path？
Question Two：What does `/X/Y/Z.png` mean
So if you see it, please reply to me, thank you very much~

**Comment by atararaksin** [comment]
Hey @wenjunzhangp, thanks for reaching out!
1. `uri` is the local path to the raster file, e.g.: `/rasters/raster.tif`
2. `X` and `Y` are do be substituted for `x` and `y` tile coordinates, and `Z` for the `zoom` number. You can read more about `xyz` concept here: https://developers.planet.com/planetschool/xyz-tiles-and-slippy-maps/

**Comment by wenjunzhangp** [comment]
Thank you very much for your reply,I am a novice in the geography industry.
I try to give a cog tif,But the server displays an exception, screenshots and stack errors are as follows.
The pictures uploaded here cannot be displayed,I sent the screenshot and error stack to your mailbox
```
[ERROR] [07/07/2020 10:08:26.447] [cog-tile-server-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(cog-tile-server)] Error during processing of request: 'assertion failed'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:208)
        at geotrellis.raster.render.MultibandColorMethods.color(ColorMethods.scala:47)
        at geotrellis.raster.render.MultibandColorMethods.color$(ColorMethods.scala:46)
        at geotrellis.raster.package$withMultibandTileMethods.color(package.scala:83)
        at geotrellis.raster.render.MultibandPngRenderMethods.renderPng(MultibandPngRenderMethods.scala:36)
        at geotrellis.raster.render.MultibandPngRenderMethods.renderPng$(MultibandPngRenderMethods.scala:35)
        at geotrellis.raster.package$withMultibandTileMethods.renderPng(package.scala:83)
        at cogtileserver.CogService$.$anonfun$getTile$1(CogService.scala:35)
        at scala.Option.map(Option.scala:163)
        at cogtileserver.CogService$.getTile(CogService.scala:35)
        at cogtileserver.TileServer$.$anonfun$route$7(TileServer.scala:26)
        at akka.http.scaladsl.server.Directive$.$anonfun$addByNameNullaryApply$2(Directive.scala:144)
        at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:197)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapInnerRoute$1(BasicDirectives.scala:37)
        at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:125)
        at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$2(Directive.scala:197)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$tprovide$1(BasicDirectives.scala:143)
        at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:125)
        at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$1(Directive.scala:197)
        at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:125)
        at akka.http.scaladsl.server.Directive.$anonfun$tflatMap$2(Directive.scala:69)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:66)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:66)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:72)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
        at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1375)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by wenjunzhangp** [comment]
If you want, please help me, thank you very much~~~

**Comment by atararaksin** [comment]
Try switching to the `gdal-raster-source` branch. This branch uses a newer `geotrellis` version which removes the necessity to use explicit caching altogether.
I think this will also resolve your issue. If it doesn't, please show the output of `gdalinfo` for your tif (e.g. `gdalinfo raster.tif`). Or, if the tif is not large and if it's ok to share it, just post your tif here, or email it.

**Comment by wenjunzhangp** [comment]
I used the `gdal-raster-source` branch. Do you have the `gdalwarp_bindings.dll` file there? Can you give me a copy if you have one? My email:`zhangwenjunp@126.com` I am reporting errors in the system log and cannot find this file. The exception is as follows:
```
java.lang.UnsatisfiedLinkError: C:\Users\wenjunzhangp\AppData\Local\Temp\nativeutils400894177705900\gdalwarp_bindings.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at cz.adamh.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:109)
	at com.azavea.gdal.GDALWarp.init(GDALWarp.java:132)
	at com.azavea.gdal.GDALWarp.<clinit>(GDALWarp.java:142)
	at geotrellis.contrib.vlm.gdal.GDALDataset$.apply(GDALDataset.scala:178)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.dataset$lzycompute(GDALRasterSource.scala:55)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.dataset(GDALRasterSource.scala:50)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.gridExtent$lzycompute(GDALRasterSource.scala:69)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.gridExtent(GDALRasterSource.scala:69)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.reproject(GDALRasterSource.scala:90)
	at geotrellis.contrib.vlm.RasterSource.reproject(RasterSource.scala:94)
	at geotrellis.contrib.vlm.RasterSource.reproject$(RasterSource.scala:93)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.reproject(GDALRasterSource.scala:31)
	at scala.CogService$.getTile(CogService.scala:16)
	at scala.TileServer$.$anonfun$route$7(TileServer.scala:26)
	at akka.http.scaladsl.server.Directive$.$anonfun$addByNameNullaryApply$2(Directive.scala:144)
	at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:197)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapInnerRoute$1(BasicDirectives.scala:37)
	at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:125)
	at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$2(Directive.scala:197)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$tprovide$1(BasicDirectives.scala:143)
	at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:125)
	at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$1(Directive.scala:197)
	at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:125)
	at akka.http.scaladsl.server.Directive.$anonfun$tflatMap$2(Directive.scala:69)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:66)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:66)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:72)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1375)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by wenjunzhangp** [comment]
I push an issue [here](https://github.com/geotrellis/gdal-warp-bindings/issues/95)
